### ISSUE TITLE
X-ui exit-code

### ISSUE THREAD

**Issue by m2tts2001** [hossinasaadi/x-ui#136]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

The panel crashes and stops randomly with the following logs. It happens on several servers that I have. I should restart the x-ui to fix it and this is so annoying. Maybe it would be good if you set self-restart for example for every 1 hour. 
Another suggestion I have. Set a daily limit usage for each client that could restart automatically at the beginning of the day.  It helps us to prevent IP blocking when a client violates and shares the config with others. In this situation, we can monitor unusual traffic on every config and if a user reaches the limit he will be disconnected until tomorrow.

### Version of x-ui

<details>

Ubuntu 20
$ x-ui version
0.5.4
```

</details>

### x-ui log or xray log

<details>

Ubuntu 20
# paste log here
```
Nov 26 14:25:53 marvelous x-ui[720]: 2022/11/26 14:25:53 WARNING - client ip job err: database is locked
Nov 26 14:25:53 marvelous x-ui[720]: panic: runtime error: invalid memory address or nil pointer dereference
Nov 26 14:25:53 marvelous x-ui[720]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0xad1281]
Nov 26 14:25:53 marvelous x-ui[720]: goroutine 1419547 [running]:
Nov 26 14:25:53 marvelous x-ui[720]: x-ui/web/job.updateInboundClientIps(0xc0005908a0, {0xc00044b8c0, 0x6}, {0xc000624570?, 0x1, 0x1})
Nov 26 14:25:53 marvelous x-ui[720]:         /home/runner/work/x-ui/x-ui/web/job/check_clinet_ip_job.go:195 +0x241
Nov 26 14:25:53 marvelous x-ui[720]: x-ui/web/job.processLogFile()
Nov 26 14:25:53 marvelous x-ui[720]:         /home/runner/work/x-ui/x-ui/web/job/check_clinet_ip_job.go:100 +0x40a
Nov 26 14:25:53 marvelous x-ui[720]: x-ui/web/job.(*CheckClientIpJob).Run(0x0?)
Nov 26 14:25:53 marvelous x-ui[720]:         /home/runner/work/x-ui/x-ui/web/job/check_clinet_ip_job.go:34 +0x65
Nov 26 14:25:53 marvelous x-ui[720]: github.com/robfig/cron/v3.(*Cron).startJob.func1()
Nov 26 14:25:53 marvelous x-ui[720]:         /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0x6a
Nov 26 14:25:53 marvelous x-ui[720]: created by github.com/robfig/cron/v3.(*Cron).startJob
Nov 26 14:25:53 marvelous x-ui[720]:         /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0xad
Nov 26 14:25:53 marvelous systemd[1]: x-ui.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Nov 26 14:25:53 marvelous systemd[1]: x-ui.service: Failed with result 'exit-code'.
</details>

**Comment by sajjad-ser** [comment]
> 

منم بعضی وفتها همینجوری میشه
